# Using YAML allows the user to change config without wasting time looking at the code
keys:
    misp_url: 'https://96.126.107.93/'
    misp_key: 'FzZF4jke5U9uB5LsZiI1VQLUNlp9Sr2ezufEcevS'
    misp_verifycert: False